### ISSUE TITLE
HA Core 2024.12

### ISSUE THREAD

**Issue by thomail** [machgo/fellerwiserhomeassistant#12]
Anyone using this integration already updated to HA Core 2024.12?
I did and had to roll back cause this integration  stopped working. Hope you're having more luck. Let me know if it was just me.
Cheers

**Comment by kess78** [comment]
I never install the .0 version... When .1 will come out I'll test it out...

**Comment by kess78** [comment]
I've upgraded my test instance to 2024.12.0 and in effect, the integration isn't working anymore.
As a quick and dirty fix, you can change the 2 following lines:

**Line 35 in cover.py:**
from:
`async with websockets.connect("ws://"+ip+"/api", extra_headers={'authorization':'Bearer ' + apikey}, ping_timeout=None) as ws:`
to:
`async with websockets.connect("ws://"+ip+"/api", additional_headers={'authorization':'Bearer ' + apikey}, ping_timeout=None) as ws:`

**Line 42 in light.py:**
from:
`async with websockets.connect("ws://"+ip+"/api", extra_headers={'authorization':'Bearer ' + apikey}, ping_timeout=None) as ws:`
to:
`async with websockets.connect("ws://"+ip+"/api", additional_headers={'authorization':'Bearer ' + apikey}, ping_timeout=None) as ws:`

When I find some time I'll try to investigate further in order to write a better solution, especially for prev installations.
Please test it out and let us know.

**Comment by thomail** [comment]
I'm back on 2024.11.3 for the moment. me wife kills me if automations stop working again! 🤕
but thanks for your help! 👍
